# -*- coding: utf-8 -*-
"""correct-bmd1905.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15rxBYOVI1dPKoqMi-hxBEmmV1klEJ3Pg
"""

import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

from transformers import pipeline
corrector = pipeline(
    "text2text-generation",
    model="bmd1905/vietnamese-correction-v2",
    device=device,
)

import pandas as pd
df = pd.read_csv("vihallu-private-test.csv")
df

texts = df["prompt"].tolist()
texts[:5]

def batch_correct(texts, max_new_tokens=256):
    outs = corrector(texts, max_new_tokens=max_new_tokens)
    return [out["generated_text"] for out in outs]

from tqdm.notebook import tqdm

def correct_texts(texts, batch_size=32):
    batched_texts = [texts[i:i + batch_size] for i in range(0, len(texts), batch_size)]

    all_corrected = []
    for batch in tqdm(batched_texts, desc="text correction"):
        corrected = batch_correct(batch)
        all_corrected.extend(corrected)

    return all_corrected

corrected_prompts = correct_texts(texts, batch_size=16)

df["prompt"] = corrected_prompts
df.to_csv("vihallu-private-test-clean-reduced.csv", index=False)
df